services:
  mysql:
    image: mysql:8.0
    ports:
      - ${DATABASE_PORT_OUTER}:${DATABASE_PORT_INNER}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
